stages:
  - build
  - deploy

variables:
  DOMAIN: "copay.prodanocontest.ru"
  BOT_TOKEN: "7571512572:AAGA3Id7R32BYysSiVh9N7suj-xKTQPmCTc" 

before_script:
  - echo "Setting up environment..."
  - export $(grep -v '^#' .env.template | xargs)

deploy:
  stage: deploy
  services:
    - docker:dind
  tags:
    - vps
  script:
    - echo "Deploying application..."
    - docker compose -f docker-compose.yml up -d --build --remove-orphans
  only:
    - master
