stages:
  - build
  - deploy

variables:
  DOMAIN: "copay.prodanocontest.ru"

before_script:
  - echo "Setting up environment..."
  - export $(grep -v '^#' .env.template | xargs)

deploy:
  stage: deploy
  services:
    - docker:dind
  tags:
    - vps
  script:
    - echo "Deploying application..."
    - echo "Using $TOKEN_TELEGRAM_API as TOKEN_TELEGRAM_API"
    - docker compose -f docker-compose.traefik.yml up -d
    - docker compose -f docker-compose.yml up -d --build --remove-orphans
  only:
    - master
