"""empty message

Revision ID: 1c08eb490914
Revises: 8c5f2b5a7ea7
Create Date: 2024-11-09 15:47:37.737627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1c08eb490914'
down_revision: Union[str, None] = '8c5f2b5a7ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('event_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'event_id')
    # ### end Alembic commands ###
