"""empty message

Revision ID: 3ca6a6b2428d
Revises: a70f17d2f4ad
Create Date: 2024-11-08 21:35:20.477298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3ca6a6b2428d'
down_revision: Union[str, None] = 'a70f17d2f4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
