"""empty message

Revision ID: 8c5f2b5a7ea7
Revises: 444a44490f39
Create Date: 2024-11-09 15:43:45.559165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '8c5f2b5a7ea7'
down_revision: Union[str, None] = '444a44490f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('transaction_id', sa.Uuid(), nullable=False))
    op.add_column('item', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'item', 'transaction', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'name')
    op.drop_column('item', 'transaction_id')
    # ### end Alembic commands ###
