"""empty message

Revision ID: cc4769ae182e
Revises: 1c08eb490914
Create Date: 2024-11-09 15:51:02.330664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cc4769ae182e'
down_revision: Union[str, None] = '1c08eb490914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'owner_id')
    # ### end Alembic commands ###
