"""add assigned_to field

Revision ID: fc46c48ccfd6
Revises: 16d5d2104082
Create Date: 2024-11-09 12:54:08.948262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fc46c48ccfd6'
down_revision: Union[str, None] = '16d5d2104082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'split')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('split', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
